// =====================================================================
// lib/estimate-approval-pdf.ts
//
// Phase C core: when a vendor estimate is finalized by the board, build the
// OFFICIAL signed copy — the chosen estimate PDF with a "Board Approval" page
// appended (each signer's name · title · date · signature) — file it on the
// MAIA work order AND push it into the CINC work order, then notify the
// board, Paola, and the winning vendor with a download link.
//
// Best-effort: the caller wraps this in try/catch so a PDF/CINC hiccup never
// blocks the approval itself.
// =====================================================================

import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import { supabaseAdmin } from '@/lib/supabase-admin'
import { saveWorkOrderFile, STORAGE_BUCKET } from '@/lib/work-order-attachments'
import { pushWorkOrderAttachments, getVendorComplianceStatus } from '@/lib/integrations/cinc'
import { signVendorUploadToken } from '@/lib/vendor-upload-token'
import { sendEmail } from '@/lib/gmail'
import { appendMessage } from '@/lib/tickets'

const PAOLA = 'service@topfloridaproperties.com'
const APP = process.env.NEXT_PUBLIC_APP_URL ?? 'https://www.pmitop.com'
const ORANGE = '#f26a1b'
const money = (n: number | null) => n == null ? '—' : `$${n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
const esc = (s: string) => (s ?? '').replace(/[<>&]/g, c => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;' }[c] ?? c))

interface Signer { name: string; title: string | null; date: string | null; signature: string | null }

/** Decode a "data:image/png;base64,..." (or raw base64) signature to bytes. */
function decodeSignature(sig: string | null): { bytes: Buffer; kind: 'png' | 'jpg' } | null {
  if (!sig) return null
  const m = /^data:image\/(png|jpe?g);base64,(.*)$/i.exec(sig.trim())
  try {
    if (m) return { bytes: Buffer.from(m[2], 'base64'), kind: m[1].toLowerCase().startsWith('jp') ? 'jpg' : 'png' }
    return { bytes: Buffer.from(sig, 'base64'), kind: 'png' }
  } catch { return null }
}

/** Append a Board Approval page (US-Letter) to `doc`. */
async function appendApprovalPage(doc: PDFDocument, ctx: {
  associationName: string; woLabel: string; vendor: string; amount: number | null; scope: string | null; signers: Signer[]
}): Promise<void> {
  const page = doc.addPage([612, 792])
  const helv = await doc.embedFont(StandardFonts.Helvetica)
  const bold = await doc.embedFont(StandardFonts.HelveticaBold)
  const navy = rgb(0.08, 0.13, 0.27)
  const gray = rgb(0.42, 0.45, 0.5)
  let y = 740

  const line = (text: string, opts: { font?: typeof helv; size?: number; color?: typeof navy; x?: number } = {}) => {
    page.drawText(text, { x: opts.x ?? 56, y, size: opts.size ?? 11, font: opts.font ?? helv, color: opts.color ?? navy })
  }

  line('PMI Top Florida Properties', { font: bold, size: 13, color: rgb(0.95, 0.42, 0.11) }); y -= 30
  line('BOARD APPROVAL', { font: bold, size: 22 }); y -= 30
  line(ctx.associationName, { font: bold, size: 13 }); y -= 18
  line(ctx.woLabel, { color: gray, size: 11 }); y -= 28

  const field = (label: string, value: string) => {
    line(label.toUpperCase(), { font: bold, size: 9, color: gray }); y -= 14
    line(value, { size: 12 }); y -= 22
  }
  field('Vendor', ctx.vendor)
  field('Approved amount', money(ctx.amount))
  if (ctx.scope) { field('Scope', ctx.scope.slice(0, 110)) }
  y -= 6
  line('Approved by the Board of Directors:', { font: bold, size: 11 }); y -= 8

  for (const s of ctx.signers) {
    y -= 64
    // signature image (if any)
    const sig = decodeSignature(s.signature)
    if (sig) {
      try {
        const img = sig.kind === 'jpg' ? await doc.embedJpg(sig.bytes) : await doc.embedPng(sig.bytes)
        const w = 150, h = (img.height / img.width) * w
        page.drawImage(img, { x: 56, y: y + 18, width: w, height: Math.min(h, 44) })
      } catch { /* skip bad image */ }
    }
    page.drawLine({ start: { x: 56, y: y + 14 }, end: { x: 320, y: y + 14 }, thickness: 0.7, color: gray })
    page.drawText(`${s.name}${s.title ? ` — ${s.title}` : ''}`, { x: 56, y: y + 2, size: 10, font: bold, color: navy })
    if (s.date) page.drawText(`Date: ${s.date}`, { x: 360, y: y + 2, size: 10, font: helv, color: gray })
  }

  y -= 50
  page.drawText(`Generated by MAIA on ${new Date().toISOString().slice(0, 10)} — official board-approved copy.`,
    { x: 56, y: Math.max(y, 40), size: 8, font: helv, color: gray })
}

/** Which compliance docs the awarded vendor is missing or has expired in CINC.
 *  Returns human-readable labels for the request email (empty = all good). */
async function missingComplianceDocs(vendorId: number | null, assocCode: string | null): Promise<string[]> {
  if (!vendorId) return []
  const s = await getVendorComplianceStatus(vendorId, assocCode).catch(() => null)
  if (!s) return []
  const out: string[] = []
  if (!s.ach.onFile) out.push('Direct-deposit (ACH) banking form')
  if (!s.w9.onFile) out.push('W-9 / tax form')
  if (!s.coi.onFile || s.coi.valid === false) out.push('Certificate of Insurance (COI)')
  if (!s.license.onFile || s.license.valid === false) out.push('Trade / business license')
  return out
}

export interface FinalizeResult { ok: boolean; attachmentId?: string; cincPushed: boolean; emailed: number; docsRequested?: string[]; losersNotified?: number; note?: string }

/** Build + file the signed approval copy and notify. Best-effort. */
export async function finalizeEstimateApproval(approvalId: string): Promise<FinalizeResult> {
  const { data: a } = await supabaseAdmin.from('estimate_approvals')
    .select('id, ticket_id, association_code, request_id, vendor_request_id, vendor_name, amount, scope')
    .eq('id', approvalId).single()
  if (!a) return { ok: false, cincPushed: false, emailed: 0, note: 'approval not found' }

  // Signers who approved, with their board title.
  const { data: reviews } = await supabaseAdmin.from('estimate_approval_reviews')
    .select('board_member_name, board_member_email, signature_image, decided_at')
    .eq('approval_id', approvalId).eq('decision', 'approve')
  const { data: members } = await supabaseAdmin.from('association_board_members')
    .select('email, role').eq('association_code', a.association_code)
  const roleByEmail = new Map((members ?? []).map(m => [(m.email as string ?? '').toLowerCase(), m.role as string | null]))
  const signers: Signer[] = (reviews ?? []).map(r => ({
    name: r.board_member_name as string,
    title: roleByEmail.get((r.board_member_email as string ?? '').toLowerCase()) ?? null,
    date: r.decided_at ? String(r.decided_at).slice(0, 10) : null,
    signature: r.signature_image as string | null,
  }))

  const { data: assocRow } = await supabaseAdmin.from('associations').select('association_name').eq('association_code', a.association_code).maybeSingle()
  const associationName = (assocRow?.association_name as string) ?? a.association_code
  const { data: ticket } = await supabaseAdmin.from('tickets').select('ticket_number, cinc_workorder_id').eq('id', a.ticket_id).maybeSingle()
  const woLabel = `${ticket?.ticket_number ?? `WO ${a.ticket_id}`} · ${a.association_code}`
  const amount = a.amount != null ? Number(a.amount) : null

  // Load the chosen estimate PDF bytes (if available).
  let estimateBytes: Buffer | null = null
  const { data: erv } = await supabaseAdmin.from('estimate_request_vendors').select('estimate_path').eq('id', a.vendor_request_id).maybeSingle()
  if (erv?.estimate_path) {
    const { data: att } = await supabaseAdmin.from('work_order_attachments').select('storage_path').eq('id', erv.estimate_path).maybeSingle()
    if (att?.storage_path) {
      const { data: blob } = await supabaseAdmin.storage.from(STORAGE_BUCKET).download(att.storage_path as string)
      if (blob) estimateBytes = Buffer.from(await blob.arrayBuffer())
    }
  }

  // Build the signed PDF: estimate (if a loadable PDF) + appended approval page.
  let doc: PDFDocument
  try {
    doc = estimateBytes && estimateBytes.subarray(0, 5).toString('latin1') === '%PDF-'
      ? await PDFDocument.load(estimateBytes, { ignoreEncryption: true })
      : await PDFDocument.create()
  } catch {
    doc = await PDFDocument.create()
  }
  await appendApprovalPage(doc, { associationName, woLabel, vendor: a.vendor_name as string ?? '—', amount, scope: a.scope as string | null, signers })
  const signedBytes = Buffer.from(await doc.save())

  // File on the MAIA work order.
  const filename = `Board Approval — ${(a.vendor_name as string ?? 'vendor').slice(0, 40)} — ${money(amount)}.pdf`.replace(/[/\\]/g, '-')
  const saved = await saveWorkOrderFile({ ticketId: a.ticket_id as number, source: 'staff_upload', bytes: signedBytes, filename, contentType: 'application/pdf', uploadedByEmail: 'maia' })
  const attachmentId = saved.ok ? saved.id : undefined

  // Signed download URL for the emails.
  let pdfUrl: string | null = null
  if (saved.ok) {
    const { data: rec } = await supabaseAdmin.from('work_order_attachments').select('storage_path').eq('id', saved.id).maybeSingle()
    if (rec?.storage_path) {
      const { data: signed } = await supabaseAdmin.storage.from(STORAGE_BUCKET).createSignedUrl(rec.storage_path as string, 60 * 60 * 24 * 14)
      pdfUrl = signed?.signedUrl ?? null
    }
  }

  // Push into the CINC work order (best-effort).
  let cincPushed = false
  if (ticket?.cinc_workorder_id) {
    try {
      await pushWorkOrderAttachments(parseInt(String(ticket.cinc_workorder_id), 10), [{ fileName: filename, file: signedBytes.toString('base64') }])
      cincPushed = true
    } catch (err) { console.warn(`[estimate-approval] CINC WO push failed: ${(err as Error).message}`) }
  }

  // Notify board signers + Paola + the winning vendor.
  let emailed = 0
  const dl = pdfUrl ? `<p><a href="${pdfUrl}" style="display:inline-block;background:${ORANGE};color:#fff;padding:10px 22px;border-radius:6px;text-decoration:none;font-weight:700">Download the signed approval →</a></p>` : ''
  const boardEmails = (reviews ?? []).map(r => r.board_member_email as string).filter(e => e && e.includes('@'))
  if (boardEmails.length || true) {
    await sendEmail({
      to: [...new Set([...boardEmails, PAOLA])],
      subject: `Board APPROVED — ${woLabel}`,
      html: `<p>The board approved the <strong>${esc(a.vendor_name as string ?? '')}</strong> estimate (${money(amount)}) for <strong>${esc(woLabel)}</strong>.</p>${dl}<p style="font-size:12px;color:#6b7280">The signed copy is filed on the work order${cincPushed ? ' and in CINC' : ''}.</p>`,
    }).then(() => { emailed += 1 }, () => null)
  }

  // ── C4: award notice to the winning vendor + auto-request any missing
  //        compliance docs (W-9 / COI / license) via the upload link. ──
  // `outcome_notified_at` makes this fire exactly once even if finalize retries.
  // vendor_email/vendor_id are read in a column-safe query so a not-yet-applied
  // migration can never blank out the award email; the outcome flag is read
  // best-effort separately.
  const { data: winner } = await supabaseAdmin.from('estimate_request_vendors')
    .select('vendor_email, vendor_id').eq('id', a.vendor_request_id).maybeSingle()
  const vendorEmail = (winner?.vendor_email as string | null) ?? null
  const winnerVendorId = winner?.vendor_id != null ? Number(winner.vendor_id) : null
  let alreadyNotified = false
  try {
    const { data: o } = await supabaseAdmin.from('estimate_request_vendors').select('outcome_notified_at').eq('id', a.vendor_request_id).maybeSingle()
    alreadyNotified = !!o?.outcome_notified_at
  } catch { /* column may predate the migration — treat as not notified */ }

  let docsRequested: string[] = []
  if (vendorEmail && vendorEmail.includes('@') && !alreadyNotified) {
    docsRequested = await missingComplianceDocs(winnerVendorId, a.association_code as string | null)
    let docsBlock = ''
    if (docsRequested.length) {
      const uploadLink = `${APP}/vendor/upload/${await signVendorUploadToken(a.ticket_id as number)}`
      const list = docsRequested.map(d => `<li>${esc(d)}</li>`).join('')
      docsBlock = `<p style="margin-top:18px">Before we schedule the work, please send us the following so your vendor file is current:</p>
        <ul>${list}</ul>
        <p><a href="${uploadLink}" style="display:inline-block;background:${ORANGE};color:#fff;padding:10px 22px;border-radius:6px;text-decoration:none;font-weight:700">Upload your documents →</a></p>`
    }
    await sendEmail({
      to: vendorEmail, replyTo: PAOLA,
      subject: `You've been awarded — ${esc(a.vendor_name as string ?? '')} · ${woLabel}`,
      html: `<p>Congratulations — the board approved your estimate of <strong>${money(amount)}</strong> for <strong>${esc(woLabel)}</strong> at ${esc(associationName)}.</p>${dl}${docsBlock}<p>Our coordinator will follow up with next steps.</p><p style="font-size:12px;color:#6b7280">Reply to reach PMI Top Florida Properties.</p>`,
    }).then(() => { emailed += 1 }, () => null)
    await supabaseAdmin.from('estimate_request_vendors')
      .update({ outcome: 'won', outcome_notified_at: new Date().toISOString() }).eq('id', a.vendor_request_id)
      .then(() => null, () => null)
  }

  // ── C6: not-selected notices to the OTHER vendors who actually quoted. ──
  // Only those who submitted an estimate (have a file or status 'submitted');
  // vendors who never responded just get the request closed (no awkward note).
  // Idempotency here is per-loser-row (outcome_notified_at), so this loop is
  // independent of the winner's flag — a partial prior run still finishes.
  let losersNotified = 0
  const loserNames: string[] = []
  if (a.request_id) {
    const { data: others } = await supabaseAdmin.from('estimate_request_vendors')
      .select('id, vendor_name, vendor_email, status, estimate_path, outcome_notified_at')
      .eq('request_id', a.request_id).neq('id', a.vendor_request_id)
    for (const v of (others ?? []) as { id: string; vendor_name: string | null; vendor_email: string | null; status: string | null; estimate_path: string | null; outcome_notified_at: string | null }[]) {
      const quoted = v.status === 'submitted' || !!v.estimate_path
      if (!quoted || v.outcome_notified_at) continue
      if (v.vendor_email && v.vendor_email.includes('@')) {
        await sendEmail({
          to: v.vendor_email, replyTo: PAOLA,
          subject: `Update on your estimate — ${woLabel}`,
          html: `<p>Hello${v.vendor_name ? ` ${esc(v.vendor_name)}` : ''},</p>
            <p>Thank you for submitting an estimate for <strong>${esc(woLabel)}</strong> at ${esc(associationName)}. After review, the board has selected another vendor for this project.</p>
            <p>We genuinely appreciate the time you put into your proposal and look forward to inviting you to quote on future work.</p>
            <p style="font-size:12px;color:#6b7280">PMI Top Florida Properties</p>`,
        }).then(() => { emailed += 1; losersNotified += 1 }, () => null)
        if (v.vendor_name) loserNames.push(v.vendor_name)
      }
      await supabaseAdmin.from('estimate_request_vendors')
        .update({ outcome: 'lost', outcome_notified_at: new Date().toISOString() }).eq('id', v.id)
        .then(() => null, () => null)
    }
    // Close the request so the follow-up cron stops nudging undecided vendors.
    await supabaseAdmin.from('estimate_requests').update({ status: 'closed' }).eq('id', a.request_id).then(() => null, () => null)
  }

  await appendMessage(a.ticket_id as number, { direction: 'internal_note', channel: 'internal', from_addr: 'maia',
    body: `📄 Official board-approved copy filed${cincPushed ? ' (MAIA + CINC)' : ''} for ${a.vendor_name} (${money(amount)}). Signed by ${signers.map(s => s.name).join(', ')}.`
      + (vendorEmail ? ` Award notice sent to the vendor${docsRequested.length ? ` (requested: ${docsRequested.join(', ')})` : ''}.` : '')
      + (losersNotified ? ` Not-selected notices sent to ${loserNames.join(', ') || `${losersNotified} vendor(s)`}.` : '') }).catch(() => null)

  return { ok: true, attachmentId, cincPushed, emailed, docsRequested, losersNotified }
}
