'use client'

import { useState } from 'react'

import { renderReportMarkdown } from '@/lib/render-report-markdown'

interface Props {
  assoc:      string
  month:      string
  monthLabel: string
}

export default function MonthlyReportGenerator({ assoc, month, monthLabel }: Props) {
  const [loading,  setLoading]  = useState(false)
  const [error,    setError]    = useState<string | null>(null)
  const [report,   setReport]   = useState<string | null>(null)
  const [reportId, setReportId] = useState<string | null>(null)
  const [copied,   setCopied]   = useState(false)

  async function generate() {
    setLoading(true)
    setError(null)
    setReport(null)
    setReportId(null)
    try {
      const res = await fetch('/api/admin/reports/monthly/generate', {
        method:  'POST',
        headers: { 'Content-Type': 'application/json' },
        body:    JSON.stringify({ assoc, month }),
      })
      const data = await res.json()
      if (!res.ok || !data.ok) throw new Error(data?.error ?? 'Report generation failed')
      setReport(data.report as string)
      setReportId((data.id as string) ?? null)
    } catch (err) {
      setError((err as Error).message)
    } finally {
      setLoading(false)
    }
  }

  const shareUrl = reportId
    ? (typeof window !== 'undefined' ? window.location.origin : '') + `/admin/reports/monthly/view/${reportId}`
    : null

  async function copyLink() {
    if (!shareUrl) return
    try {
      await navigator.clipboard.writeText(shareUrl)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      setError('Could not copy to clipboard')
    }
  }

  return (
    <section className="bg-white border border-gray-200 rounded-lg p-4">
      <div className="flex items-center justify-between gap-3 flex-wrap">
        <div>
          <h2 className="text-sm font-semibold text-gray-900">MAIA board report</h2>
          <p className="text-xs text-gray-500 mt-0.5">
            MAIA writes the full board report for {monthLabel}
            {assoc ? ` (${assoc})` : ' — all associations'} from the activity and the items above.
          </p>
        </div>
        <button
          onClick={() => void generate()}
          disabled={loading}
          className="bg-[#f26a1b] text-white text-sm font-medium px-4 py-1.5 rounded hover:bg-[#d85a14] disabled:opacity-50"
        >
          {loading ? 'Generating…' : report ? 'Regenerate' : 'Generate board report'}
        </button>
      </div>

      {loading && (
        <div className="mt-4 text-xs text-gray-500">
          MAIA is reviewing the month&apos;s tickets, work orders and communications…
        </div>
      )}

      {error && (
        <div className="mt-4 text-xs text-red-700 bg-red-50 border border-red-200 rounded px-3 py-2">
          {error}
        </div>
      )}

      {report && !loading && (
        <div className="mt-4 border-t border-gray-100 pt-4">
          {reportId && (
            <div className="flex flex-wrap items-center gap-2 mb-3">
              <a
                href={`/admin/reports/monthly/view/${reportId}`}
                target="_blank"
                rel="noopener noreferrer"
                className="text-xs font-medium px-3 py-1.5 rounded bg-[#f26a1b] text-white hover:bg-[#d85a14]"
              >
                Open shareable report ↗
              </a>
              <button
                onClick={() => void copyLink()}
                className="text-xs px-3 py-1.5 rounded border border-gray-200 text-gray-700 hover:border-gray-400"
              >
                {copied ? 'Link copied ✓' : 'Copy report link'}
              </button>
              <span className="text-[11px] text-gray-400">
                Saved — the link opens the full report page (staff login required).
              </span>
            </div>
          )}
          <div className="rounded-lg border border-gray-200 bg-gray-50 px-5 py-4 max-h-[560px] overflow-y-auto">
            {renderReportMarkdown(report)}
          </div>
          <p className="text-[11px] text-gray-400 mt-2">
            Draft generated by MAIA — review before sending to the board.
          </p>
        </div>
      )}
    </section>
  )
}
