// =====================================================================
// GET /api/admin/reports/monthly/[id]/pdf
//
// Server-side PDF of a saved monthly management report. Produces a true
// PDF (@react-pdf/renderer) with the navy header bar repeated on every
// page after the first and deterministic page breaks — unlike browser
// "Save as PDF". Staff-only.
// =====================================================================

import { NextResponse } from 'next/server'
import { cookies } from 'next/headers'
import { renderToBuffer } from '@react-pdf/renderer'

import { verifySession, SESSION_COOKIE } from '@/lib/session'
import { supabaseAdmin } from '@/lib/supabase-admin'
import { gatherMonthlyReportData, monthLabel } from '@/lib/monthly-report'
import { MonthlyReportPdf } from '@/lib/monthly-report-pdf'

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'
export const maxDuration = 120

/** Fetch the PMI logo and return it as a data URI, or '' on failure. */
async function loadLogo(): Promise<string> {
  try {
    const base = process.env.NEXT_PUBLIC_APP_URL ?? 'https://www.pmitop.com'
    const res  = await fetch(`${base}/pmi-logo-white.png`, { cache: 'force-cache' })
    if (!res.ok) return ''
    const buf = Buffer.from(await res.arrayBuffer())
    return `data:image/png;base64,${buf.toString('base64')}`
  } catch {
    return ''
  }
}

export async function GET(_req: Request, ctx: { params: Promise<{ id: string }> }) {
  const cookieStore = await cookies()
  const token       = cookieStore.get(SESSION_COOKIE)?.value
  const session     = token ? await verifySession(token) : null
  if (!session || session.persona !== 'staff') {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const { id } = await ctx.params

  const { data, error } = await supabaseAdmin
    .from('monthly_reports')
    .select('id, association_code, month, report_markdown, generated_by_email, generated_at')
    .eq('id', id)
    .maybeSingle()
  if (error || !data) {
    return NextResponse.json({ error: 'Report not found' }, { status: 404 })
  }

  const code = data.association_code as string
  let assocName: string | null = null
  if (code && code !== 'ALL') {
    const { data: a } = await supabaseAdmin
      .from('associations')
      .select('association_name')
      .eq('association_code', code)
      .maybeSingle()
    assocName = (a?.association_name as string | undefined) ?? null
  }
  const scopeLabel = code === 'ALL'
    ? 'All Associations'
    : (assocName ? `${assocName} (${code})` : code)

  const reportData = await gatherMonthlyReportData(code === 'ALL' ? '' : code, data.month as string)
  const logo       = await loadLogo()

  const generatedLine =
    `Generated by MAIA · PMI Top Florida Properties · ` +
    `${new Date(data.generated_at as string).toLocaleString('en-US', { dateStyle: 'long', timeStyle: 'short' })}` +
    (data.generated_by_email ? ` by ${data.generated_by_email}` : '')

  let pdf: Buffer
  try {
    pdf = await renderToBuffer(
      MonthlyReportPdf({
        scopeLabel,
        monthLabel:  monthLabel(data.month as string),
        markdown:    (data.report_markdown as string) ?? '',
        generatedLine,
        logoDataUri: logo,
        totals:      reportData.totals,
      }),
    )
  } catch (err) {
    return NextResponse.json(
      { error: `PDF generation failed: ${err instanceof Error ? err.message : String(err)}` },
      { status: 500 },
    )
  }

  const fileName = `Monthly Report - ${scopeLabel} ${monthLabel(data.month as string)}.pdf`
    .replace(/[^\w.\- ]/g, '')

  return new NextResponse(new Uint8Array(pdf), {
    status: 200,
    headers: {
      'Content-Type':        'application/pdf',
      'Content-Disposition': `attachment; filename="${fileName}"`,
      'Cache-Control':       'no-store',
    },
  })
}
